import { Injectable } from '@angular/core';
import { BehaviorSubject, map, Observable } from 'rxjs';
import { Frame } from '../bees.model';

@Injectable({
  providedIn: 'root'
})
export class FramesService {
  addNewFrame(newFrameSideA: any) {
    throw new Error('Method not implemented.');
  }
  private _frames = new BehaviorSubject<Frame[]>([
    new Frame(1, 1, 1, 'Box 1', '1A', true, false, true, true, false),
    new Frame(2, 1, 1, 'Box 1', '1B', false, false, false, true, false),
    new Frame(3, 1, 1, 'Box 1', '2A', false, false, true, true, true),
    new Frame(4, 1, 1, 'Box 1', '2B', true, false, true, true, false),
    new Frame(5, 1, 1, 'Box 1', '3A', false, false, true, true, true),
    new Frame(6, 1, 1, 'Box 1', '3B', true, false, true, true, false),
    new Frame(7, 1, 1, 'Box 1', '4A', false, false, true, false, true),
    new Frame(8, 1, 1, 'Box 1', '5B', true, false, false, true, false),
    new Frame(9, 1, 1, 'Box 1', '5A', false, true, true, false, true),
    new Frame(10, 1, 1, 'Box 1', '5B', false, true, true, true, false),
    new Frame(21, 2, 1, 'Box 2', '1A', true, false, true, true, false),
    new Frame(22, 2, 1, 'Box 2', '1B', false, false, false, true, false),
    new Frame(23, 2, 1, 'Box 2', '2A', false, false, true, true, true),
    new Frame(24, 2, 1, 'Box 2', '2B', true, false, true, true, false),
    new Frame(25, 2, 1, 'Box 2', '3A', false, false, true, true, true),
    new Frame(26, 2, 1, 'Box 2', '3B', true, false, true, true, false),
    new Frame(27, 2, 1, 'Box 2', '4A', false, false, true, false, true),
    new Frame(28, 2, 1, 'Box 2', '5B', true, false, false, true, false),
    new Frame(29, 2, 1, 'Box 2', '5A', false, true, true, false, true),
    new Frame(30, 2, 1, 'Box 2', '5B', false, true, true, true, false),
    new Frame(41, 3, 1, 'Box 3', '1A', true, false, true, true, false),
    new Frame(42, 3, 1, 'Box 3', '1B', false, false, false, true, false),
    new Frame(43, 3, 1, 'Box 3', '2A', false, false, true, true, true),
    new Frame(44, 3, 1, 'Box 3', '2B', true, false, true, true, false),
    new Frame(45, 3, 1, 'Box 3', '3A', false, false, true, true, true),
    new Frame(46, 3, 1, 'Box 3', '3B', true, false, true, true, false),
    new Frame(47, 3, 1, 'Box 3', '4A', false, false, true, false, true),
    new Frame(48, 3, 1, 'Box 3', '5B', true, false, false, true, false),
    new Frame(49, 3, 1, 'Box 3', '5A', false, true, true, false, true),
    new Frame(50, 3, 1, 'Box 3', '5B', false, true, true, true, false),
    new Frame(51, 1, 2, 'Box 1', '1A', false, true, false, false, true),
    new Frame(52, 1, 2, 'Box 1', '1B', false, false, true, false, true),
    new Frame(53, 1, 2, 'Box 1', '2A', false, false, true, true, true),
    new Frame(54, 1, 2, 'Box 1', '2B', false, false, true, true, false),
    new Frame(55, 1, 2, 'Box 1', '3A', true, false, true, true, false),
    new Frame(56, 1, 2, 'Box 1', '3B', false, true, true, false, false),
    new Frame(57, 1, 2, 'Box 1', '4A', false, true, true, false, true),
    new Frame(58, 1, 2, 'Box 1', '4B', false, true, true, true, false),
    new Frame(59, 1, 2, 'Box 1', '5A', false, false, false, false, true),
    new Frame(60, 1, 2, 'Box 1', '5B', true, true, true, false, false),
    new Frame(61, 2, 2, 'Box 2', '1A', true, true, false, false, false),
    new Frame(62, 2, 2, 'Box 2', '1B', false, false, true, false, true),
    new Frame(63, 2, 2, 'Box 2', '2A', false, true, true, false, true),
    new Frame(64, 2, 2, 'Box 2', '2B', true, true, true, false, true),
    new Frame(65, 2, 2, 'Box 2', '3A', false, false, false, false, true),
    new Frame(66, 2, 2, 'Box 2', '3B', false, true, true, false, false),
    new Frame(67, 2, 2, 'Box 2', '4A', true, false, true, false, true),
    new Frame(68, 2, 2, 'Box 2', '4B', false, true, true, false, true),
    new Frame(69, 2, 2, 'Box 2', '5A', false, false, true, false, false),
    new Frame(70, 2, 2, 'Box 2', '5B', true, true, true, true, false),
    new Frame(71, 3, 2, 'Box 3', '1A', false, false, true, true, false),
    new Frame(72, 3, 2, 'Box 3', '1B', false, true, true, true, true),
    new Frame(73, 3, 2, 'Box 3', '2A', false, true, true, true, false),
    new Frame(74, 3, 2, 'Box 3', '2B', false, true, true, true, false),
    new Frame(75, 3, 2, 'Box 3', '3A', false, false, false, true, true),
    new Frame(76, 3, 2, 'Box 3', '3B', true, true, true, true, true),
    new Frame(77, 3, 2, 'Box 3', '4A', true, false, false, true, true),
    new Frame(78, 3, 2, 'Box 3', '4B', true, true, false, false, true),
    new Frame(79, 3, 2, 'Box 3', '5A', false, true, false, true, true),
    new Frame(80, 3, 2, 'Box 3', '5B', true, false, false, false, true),
    new Frame(81, 1, 3, 'Box 1', '1A', true, true, false, true, true),
    new Frame(82, 1, 3, 'Box 1', '1B', true, true, false, true, false),
    new Frame(83, 1, 3, 'Box 1', '2A', true, true, false, false, true),
    new Frame(84, 1, 3, 'Box 1', '2B', false, true, false, true, true),
    new Frame(85, 1, 3, 'Box 1', '3A', true, true, false, true, false),
    new Frame(86, 1, 3, 'Box 1', '3B', false, true, false, false, true),
    new Frame(87, 1, 3, 'Box 1', '4A', false, false, false, true, false),
    new Frame(88, 1, 3, 'Box 1', '4B', true, true, false, true, false),
    new Frame(89, 1, 3, 'Box 1', '5A', true, true, true, false, true),
    new Frame(90, 1, 3, 'Box 1', '5B', false, true, false, true, false),
    new Frame(91, 2, 3, 'Box 2', '1A', false, false, false, true, false),
    new Frame(92, 2, 3, 'Box 2', '1B', true, true, true, false, true),
    new Frame(93, 2, 3, 'Box 2', '2A', false, true, false, true, true),
    new Frame(94, 2, 3, 'Box 2', '2B', true, true, false, true, true),
    new Frame(95, 2, 3, 'Box 2', '3A', true, false, true, false, false),
    new Frame(96, 2, 3, 'Box 2', '3B', true, true, false, true, true),
    new Frame(97, 2, 3, 'Box 2', '4A', true, true, true, true, true),
    new Frame(98, 2, 3, 'Box 2', '4B', true, true, true, false, false),
    new Frame(99, 2, 3, 'Box 2', '5A', false, false, false, false, true),
    new Frame(100, 2, 3, 'Box 2', '5B', true, true, false, false, true),
    new Frame(101, 3, 3, 'Box 3', '1A', true, false, false, false, true),
    new Frame(102, 3, 3, 'Box 3', '1B', true, true, false, false, true),
    new Frame(103, 3, 3, 'Box 3', '2A', true, true, false, false, false),
    new Frame(104, 3, 3, 'Box 3', '2B', true, false, false, true, true),
    new Frame(105, 3, 3, 'Box 3', '3A', true, false, false, false, false),
    new Frame(106, 3, 3, 'Box 3', '3B', true, false, true, false, false),
    new Frame(107, 3, 3, 'Box 3', '4A', true, false, false, true, true),
    new Frame(108, 3, 3, 'Box 3', '4B', false, false, true, true, true),
    new Frame(109, 3, 3, 'Box 3', '5A', true, true, false, true, false),
    new Frame(110, 3, 3, 'Box 3', '5B', true, true, false, true, true),
    new Frame(111, 1, 4, 'Box 1', '1A', false, false, true, true, false),
    new Frame(112, 1, 4, 'Box 1', '1B', true, true, true, true, false),
    new Frame(113, 1, 4, 'Box 1', '2A', true, true, true, false, true),
    new Frame(114, 1, 4, 'Box 1', '2B', true, false, false, false, true),
    new Frame(115, 1, 4, 'Box 1', '3A', true, false, false, false, false),
    new Frame(116, 1, 4, 'Box 1', '3B', true, true, false, false, true),
    new Frame(117, 1, 4, 'Box 1', '4A', false, false, true, true, true),
    new Frame(118, 1, 4, 'Box 1', '4B', true, true, true, false, true),
    new Frame(119, 1, 4, 'Box 1', '5A', true, false, false, true, true),
    new Frame(120, 1, 4, 'Box 1', '5B', true, false, false, false, false),
    new Frame(121, 2, 4, 'Box 2', '1A', false, false, true, true, false),
    new Frame(122, 2, 4, 'Box 2', '1B', false, true, true, true, true),
    new Frame(123, 2, 4, 'Box 2', '2A', false, true, false, false, true),
    new Frame(124, 2, 4, 'Box 2', '2B', true, true, false, false, false),
    new Frame(125, 2, 4, 'Box 2', '3A', true, false, false, true, true),
    new Frame(126, 2, 4, 'Box 2', '3B', true, true, false, true, true),
    new Frame(127, 2, 4, 'Box 2', '4A', false, false, false, true, true),
    new Frame(128, 2, 4, 'Box 2', '4B', true, false, false, false, true),
    new Frame(129, 2, 4, 'Box 2', '5A', true, false, false, false, true),
    new Frame(130, 2, 4, 'Box 2', '5B', false, false, false, false, true),
    new Frame(131, 3, 4, 'Box 3', '1A', false, true, true, true, true),
    new Frame(132, 3, 4, 'Box 3', '1B', false, false, true, true, false),
    new Frame(133, 3, 4, 'Box 3', '2A', false, true, false, false, true),
    new Frame(134, 3, 4, 'Box 3', '2B', false, true, false, true, true),
    new Frame(135, 3, 4, 'Box 3', '3A', false, true, true, false, true),
    new Frame(136, 3, 4, 'Box 3', '3B', true, false, false, false, false),
    new Frame(137, 3, 4, 'Box 3', '4A', false, true, false, false, true),
    new Frame(138, 3, 4, 'Box 3', '4B', true, true, false, false, false),
    new Frame(139, 3, 4, 'Box 3', '5A', true, false, false, false, false),
    new Frame(140, 3, 4, 'Box 3', '5B', false, true, true, true, true),
    new Frame(141, 1, 5, 'Box 1', '1A', true, true, false, true, true),
    new Frame(142, 1, 5, 'Box 1', '1B', false, true, false, false, false),
    new Frame(143, 1, 5, 'Box 1', '2A', false, true, true, true, false),
    new Frame(144, 1, 5, 'Box 1', '2B', true, true, false, true, true),
    new Frame(145, 1, 5, 'Box 1', '3A', false, true, false, false, true),
    new Frame(146, 1, 5, 'Box 1', '3B', false, false, false, true, true),
    new Frame(147, 1, 5, 'Box 1', '4A', true, true, false, false, true),
    new Frame(148, 1, 5, 'Box 1', '4B', true, true, true, false, true),
    new Frame(149, 1, 5, 'Box 1', '5A', false, false, true, false, false),
    new Frame(150, 1, 5, 'Box 1', '5B', false, false, true, false, true),
    new Frame(151, 2, 5, 'Box 2', '1A', false, true, true, true, true),
    new Frame(152, 2, 5, 'Box 2', '1B', false, true, false, false, true),
    new Frame(153, 2, 5, 'Box 2', '2A', true, true, false, true, false),
    new Frame(154, 2, 5, 'Box 2', '2B', true, false, false, false, false),
    new Frame(155, 2, 5, 'Box 2', '3A', true, true, true, true, true),
    new Frame(156, 2, 5, 'Box 2', '3B', true, false, true, false, false),
    new Frame(157, 2, 5, 'Box 2', '4A', false, true, false, true, true),
    new Frame(158, 2, 5, 'Box 2', '4B', true, true, true, false, false),
    new Frame(159, 2, 5, 'Box 2', '5A', true, false, false, false, false),
    new Frame(160, 2, 5, 'Box 2', '5B', false, false, true, false, false),
    new Frame(161, 3, 5, 'Box 3', '1A', false, true, true, false, true),
    new Frame(162, 3, 5, 'Box 3', '1B', false, true, false, false, false),
    new Frame(163, 3, 5, 'Box 3', '2A', true, false, false, false, true),
    new Frame(164, 3, 5, 'Box 3', '2B', false, true, true, false, false),
    new Frame(165, 3, 5, 'Box 3', '3A', false, true, true, false, true),
    new Frame(166, 3, 5, 'Box 3', '3B', false, false, false, false, false),
    new Frame(167, 3, 5, 'Box 3', '4A', true, false, false, true, false),
    new Frame(168, 3, 5, 'Box 3', '4B', false, false, true, true, false),
    new Frame(169, 3, 5, 'Box 3', '5A', true, true, true, true, false),
    new Frame(170, 3, 5, 'Box 3', '5B', true, true, true, true, true),
    new Frame(171, 1, 6, 'Box 1', '1A', false, false, true, false, false),
    new Frame(172, 1, 6, 'Box 1', '1B', false, false, false, false, true),
    new Frame(173, 1, 6, 'Box 1', '2A', true, true, false, true, true),
    new Frame(174, 1, 6, 'Box 1', '2B', true, true, true, false, false),
    new Frame(175, 1, 6, 'Box 1', '3A', false, true, true, false, false),
    new Frame(176, 1, 6, 'Box 1', '3B', true, false, true, false, true),
    new Frame(177, 1, 6, 'Box 1', '4A', true, false, false, false, true),
    new Frame(178, 1, 6, 'Box 1', '4B', false, false, false, true, true),
    new Frame(179, 1, 6, 'Box 1', '5A', false, false, true, false, true),
    new Frame(180, 1, 6, 'Box 1', '5B', false, false, true, true, true),
    new Frame(181, 2, 6, 'Box 2', '1A', true, false, false, true, true),
    new Frame(182, 2, 6, 'Box 2', '1B', false, false, true, true, false),
    new Frame(183, 2, 6, 'Box 2', '2A', true, true, false, true, false),
    new Frame(184, 2, 6, 'Box 2', '2B', true, false, false, false, true),
    new Frame(185, 2, 6, 'Box 2', '3A', false, true, false, true, true),
    new Frame(186, 2, 6, 'Box 2', '3B', false, false, false, false, true),
    new Frame(187, 2, 6, 'Box 2', '4A', true, false, false, false, false),
    new Frame(188, 2, 6, 'Box 2', '4B', true, true, false, true, true),
    new Frame(189, 2, 6, 'Box 2', '5A', false, false, false, false, false),
    new Frame(190, 2, 6, 'Box 2', '5B', true, false, true, false, false),
    new Frame(191, 3, 6, 'Box 3', '1A', true, false, false, false, false),
    new Frame(192, 3, 6, 'Box 3', '1B', false, true, true, false, true),
    new Frame(193, 3, 6, 'Box 3', '2A', true, true, false, false, true),
    new Frame(194, 3, 6, 'Box 3', '2B', true, true, true, false, true),
    new Frame(195, 3, 6, 'Box 3', '3A', true, true, false, true, false),
    new Frame(196, 3, 6, 'Box 3', '3B', false, true, false, false, true),
    new Frame(197, 3, 6, 'Box 3', '4A', false, false, false, true, true),
    new Frame(198, 3, 6, 'Box 3', '4B', false, true, true, false, false),
    new Frame(199, 3, 6, 'Box 3', '5A', true, false, true, true, false),
    new Frame(200, 3, 6, 'Box 3', '5B', true, true, false, true, true),
    new Frame(201, 1, 7, 'Box 1', '1A', true, false, false, true, true),
    new Frame(202, 1, 7, 'Box 1', '1B', true, false, true, true, true),
    new Frame(203, 1, 7, 'Box 1', '2A', false, true, false, true, false),
    new Frame(204, 1, 7, 'Box 1', '2B', false, false, false, true, false),
    new Frame(205, 1, 7, 'Box 1', '3A', false, false, true, false, false),
    new Frame(206, 1, 7, 'Box 1', '3B', false, false, true, true, true),
    new Frame(207, 1, 7, 'Box 1', '4A', false, true, false, true, false),
    new Frame(208, 1, 7, 'Box 1', '4B', true, true, true, false, true),
    new Frame(209, 1, 7, 'Box 1', '5A', false, false, true, false, true),
    new Frame(210, 1, 7, 'Box 1', '5B', true, true, true, true, true),
    new Frame(211, 2, 7, 'Box 2', '1A', true, false, true, false, true),
    new Frame(212, 2, 7, 'Box 2', '1B', true, true, true, false, true),
    new Frame(213, 2, 7, 'Box 2', '2A', true, false, true, true, false),
    new Frame(214, 2, 7, 'Box 2', '2B', false, false, true, true, false),
    new Frame(215, 2, 7, 'Box 2', '3A', true, false, false, true, false),
    new Frame(216, 2, 7, 'Box 2', '3B', true, true, false, false, false),
    new Frame(217, 2, 7, 'Box 2', '4A', true, true, true, false, false),
    new Frame(218, 2, 7, 'Box 2', '4B', true, true, true, false, true),
    new Frame(219, 2, 7, 'Box 2', '5A', false, true, true, false, true),
    new Frame(220, 2, 7, 'Box 2', '5B', false, true, false, true, true),
    new Frame(221, 3, 7, 'Box 3', '1A', true, true, false, false, true),
    new Frame(222, 3, 7, 'Box 3', '1B', true, true, true, false, true),
    new Frame(223, 3, 7, 'Box 3', '2A', false, true, true, false, true),
    new Frame(224, 3, 7, 'Box 3', '2B', true, false, true, true, true),
    new Frame(225, 3, 7, 'Box 3', '3A', false, false, true, false, false),
    new Frame(226, 3, 7, 'Box 3', '3B', true, false, false, true, false),
    new Frame(227, 3, 7, 'Box 3', '4A', false, true, false, true, true),
    new Frame(228, 3, 7, 'Box 3', '4B', true, true, true, true, false),
    new Frame(229, 3, 7, 'Box 3', '5A', false, true, false, true, false),
    new Frame(230, 3, 7, 'Box 3', '5B', false, false, true, false, true),
    new Frame(231, 1, 8, 'Box 1', '1A', true, true, false, false, false),
    new Frame(232, 1, 8, 'Box 1', '1B', false, true, true, true, false),
    new Frame(233, 1, 8, 'Box 1', '2A', true, false, false, false, false),
    new Frame(234, 1, 8, 'Box 1', '2B', false, false, true, true, true),
    new Frame(235, 1, 8, 'Box 1', '3A', false, false, true, false, true),
    new Frame(236, 1, 8, 'Box 1', '3B', true, false, false, false, true),
    new Frame(237, 1, 8, 'Box 1', '4A', true, true, true, false, true),
    new Frame(238, 1, 8, 'Box 1', '4B', true, false, false, true, false),
    new Frame(239, 1, 8, 'Box 1', '5A', false, true, true, false, false),
    new Frame(240, 1, 8, 'Box 1', '5B', true, false, true, true, true),
    new Frame(241, 2, 8, 'Box 2', '1A', true, false, true, true, false),
    new Frame(242, 2, 8, 'Box 2', '1B', true, true, false, false, false),
    new Frame(243, 2, 8, 'Box 2', '2A', true, false, true, false, true),
    new Frame(244, 2, 8, 'Box 2', '2B', false, false, false, false, true),
    new Frame(245, 2, 8, 'Box 2', '3A', false, false, false, false, true),
    new Frame(246, 2, 8, 'Box 2', '3B', true, true, true, true, true),
    new Frame(247, 2, 8, 'Box 2', '4A', true, false, true, true, false),
    new Frame(248, 2, 8, 'Box 2', '4B', false, true, true, false, true),
    new Frame(249, 2, 8, 'Box 2', '5A', true, false, false, false, true),
    new Frame(250, 2, 8, 'Box 2', '5B', true, true, true, true, false),
    new Frame(251, 3, 8, 'Box 3', '1A', true, true, false, true, true),
    new Frame(252, 3, 8, 'Box 3', '1B', false, false, false, true, false),
    new Frame(253, 3, 8, 'Box 3', '2A', false, true, false, true, true),
    new Frame(254, 3, 8, 'Box 3', '2B', true, false, false, true, true),
    new Frame(255, 3, 8, 'Box 3', '3A', false, true, false, false, false),
    new Frame(256, 3, 8, 'Box 3', '3B', false, false, false, true, false),
    new Frame(257, 3, 8, 'Box 3', '4A', true, true, false, true, false),
    new Frame(258, 3, 8, 'Box 3', '4B', true, false, true, false, false),
    new Frame(259, 3, 8, 'Box 3', '5A', false, true, true, true, true),
    new Frame(260, 3, 8, 'Box 3', '5B', false, false, false, true, false),
    new Frame(261, 1, 9, 'Box 1', '1A', true, false, true, false, true),
    new Frame(262, 1, 9, 'Box 1', '1B', false, false, false, false, false),
    new Frame(263, 1, 9, 'Box 1', '2A', true, false, true, true, true),
    new Frame(264, 1, 9, 'Box 1', '2B', true, true, true, true, false),
    new Frame(265, 1, 9, 'Box 1', '3A', true, true, true, false, true),
    new Frame(266, 1, 9, 'Box 1', '3B', true, true, true, true, false),
    new Frame(267, 1, 9, 'Box 1', '4A', false, false, false, true, false),
    new Frame(268, 1, 9, 'Box 1', '4B', true, true, false, false, true),
    new Frame(269, 1, 9, 'Box 1', '5A', false, true, true, true, false),
    new Frame(270, 1, 9, 'Box 1', '5B', true, true, false, false, true),
    new Frame(271, 2, 9, 'Box 2', '1A', true, true, true, true, true),
    new Frame(272, 2, 9, 'Box 2', '1B', false, false, false, true, false),
    new Frame(273, 2, 9, 'Box 2', '2A', true, true, true, true, true),
    new Frame(274, 2, 9, 'Box 2', '2B', false, true, true, false, true),
    new Frame(275, 2, 9, 'Box 2', '3A', true, true, true, true, true),
    new Frame(276, 2, 9, 'Box 2', '3B', true, true, true, true, true),
    new Frame(277, 2, 9, 'Box 2', '4A', true, true, false, true, false),
    new Frame(278, 2, 9, 'Box 2', '4B', true, true, false, false, true),
    new Frame(279, 2, 9, 'Box 2', '5A', true, false, true, false, true),
    new Frame(280, 2, 9, 'Box 2', '5B', false, false, false, false, true),
    new Frame(281, 3, 9, 'Box 3', '1A', true, true, true, true, false),
    new Frame(282, 3, 9, 'Box 3', '1B', false, false, true, true, true),
    new Frame(283, 3, 9, 'Box 3', '2A', true, false, false, false, true),
    new Frame(284, 3, 9, 'Box 3', '2B', false, true, false, false, false),
    new Frame(285, 3, 9, 'Box 3', '3A', false, false, true, false, true),
    new Frame(286, 3, 9, 'Box 3', '3B', true, false, true, false, false),
    new Frame(287, 3, 9, 'Box 3', '4A', true, false, false, true, false),
    new Frame(288, 3, 9, 'Box 3', '4B', false, true, true, false, false),
    new Frame(289, 3, 9, 'Box 3', '5A', true, false, true, false, false),
    new Frame(290, 3, 9, 'Box 3', '5B', true, false, false, false, true),
    new Frame(291, 1, 10, 'Box 1', '1A', true, false, true, true, true),
    new Frame(292, 1, 10, 'Box 1', '1B', false, false, false, false, false),
    new Frame(293, 1, 10, 'Box 1', '2A', true, true, true, true, false),
    new Frame(294, 1, 10, 'Box 1', '2B', false, true, false, false, false),
    new Frame(295, 1, 10, 'Box 1', '3A', true, false, true, false, false),
    new Frame(296, 1, 10, 'Box 1', '3B', false, false, false, false, true),
    new Frame(297, 1, 10, 'Box 1', '4A', true, true, true, true, true),
    new Frame(298, 1, 10, 'Box 1', '4B', true, true, true, true, false),
    new Frame(299, 1, 10, 'Box 1', '5A', false, false, false, false, false),
    new Frame(300, 1, 10, 'Box 1', '5B', false, false, true, false, false),
    new Frame(301, 2, 10, 'Box 2', '1A', true, true, true, false, true),
    new Frame(302, 2, 10, 'Box 2', '1B', false, false, true, true, false),
    new Frame(303, 2, 10, 'Box 2', '2A', false, true, false, false, false),
    new Frame(304, 2, 10, 'Box 2', '2B', true, false, false, true, true),
    new Frame(305, 2, 10, 'Box 2', '3A', true, true, true, false, true),
    new Frame(306, 2, 10, 'Box 2', '3B', false, true, false, false, false),
    new Frame(307, 2, 10, 'Box 2', '4A', false, false, true, true, true),
    new Frame(308, 2, 10, 'Box 2', '4B', true, true, true, true, false),
    new Frame(309, 2, 10, 'Box 2', '5A', false, true, false, false, true),
    new Frame(310, 2, 10, 'Box 2', '5B', true, true, true, true, true),
    new Frame(311, 3, 10, 'Box 3', '1A', false, true, false, false, true),
    new Frame(312, 3, 10, 'Box 3', '1B', true, false, true, true, true),
    new Frame(313, 3, 10, 'Box 3', '2A', false, false, true, false, false),
    new Frame(314, 3, 10, 'Box 3', '2B', true, false, true, false, true),
    new Frame(315, 3, 10, 'Box 3', '3A', false, false, true, true, true),
    new Frame(316, 3, 10, 'Box 3', '3B', true, true, true, true, false),
    new Frame(317, 3, 10, 'Box 3', '4A', false, true, false, true, false),
    new Frame(318, 3, 10, 'Box 3', '4B', true, true, true, true, false),
    new Frame(319, 3, 10, 'Box 3', '5A', true, true, false, false, true),
    new Frame(320, 3, 10, 'Box 3', '5B', false, true, false, false, false),
    new Frame(321, 1, 11, 'Box 1', '1A', true, true, true, true, true),
    new Frame(322, 1, 11, 'Box 1', '1B', false, false, true, false, true),
    new Frame(323, 1, 11, 'Box 1', '2A', false, true, false, false, false),
    new Frame(324, 1, 11, 'Box 1', '2B', false, false, false, false, true),
    new Frame(325, 1, 11, 'Box 1', '3A', true, false, true, true, true),
    new Frame(326, 1, 11, 'Box 1', '3B', false, false, false, true, true),
    new Frame(327, 1, 11, 'Box 1', '4A', true, true, false, true, false),
    new Frame(328, 1, 11, 'Box 1', '4B', false, true, true, true, true),
    new Frame(329, 1, 11, 'Box 1', '5A', true, true, false, true, true),
    new Frame(330, 1, 11, 'Box 1', '5B', true, true, true, false, true),
    new Frame(331, 2, 11, 'Box 2', '1A', true, false, true, false, true),
    new Frame(332, 2, 11, 'Box 2', '1B', false, false, false, false, true),
    new Frame(333, 2, 11, 'Box 2', '2A', false, false, true, true, true),
    new Frame(334, 2, 11, 'Box 2', '2B', false, false, true, true, true),
    new Frame(335, 2, 11, 'Box 2', '3A', true, true, true, true, true),
    new Frame(336, 2, 11, 'Box 2', '3B', true, true, false, false, false),
    new Frame(337, 2, 11, 'Box 2', '4A', true, false, true, true, true),
    new Frame(338, 2, 11, 'Box 2', '4B', false, true, false, false, false),
    new Frame(339, 2, 11, 'Box 2', '5A', true, false, true, false, false),
    new Frame(340, 2, 11, 'Box 2', '5B', false, true, false, true, false),
    new Frame(341, 3, 11, 'Box 3', '1A', true, true, true, true, false),
    new Frame(342, 3, 11, 'Box 3', '1B', true, false, false, true, false),
    new Frame(343, 3, 11, 'Box 3', '2A', false, true, true, false, false),
    new Frame(344, 3, 11, 'Box 3', '2B', false, true, true, true, false),
    new Frame(345, 3, 11, 'Box 3', '3A', true, true, true, true, false),
    new Frame(346, 3, 11, 'Box 3', '3B', false, false, false, false, true),
    new Frame(347, 3, 11, 'Box 3', '4A', false, true, false, true, true),
    new Frame(348, 3, 11, 'Box 3', '4B', true, false, true, false, false),
    new Frame(349, 3, 11, 'Box 3', '5A', true, false, true, true, false),
    new Frame(350, 3, 11, 'Box 3', '5B', false, false, true, true, true),
    new Frame(351, 1, 12, 'Box 1', '1A', false, false, false, false, true),
    new Frame(352, 1, 12, 'Box 1', '1B', false, true, false, false, false),
    new Frame(353, 1, 12, 'Box 1', '2A', true, true, false, false, false),
    new Frame(354, 1, 12, 'Box 1', '2B', false, false, true, false, true),
    new Frame(355, 1, 12, 'Box 1', '3A', true, true, false, true, false),
    new Frame(356, 1, 12, 'Box 1', '3B', false, true, false, false, true),
    new Frame(357, 1, 12, 'Box 1', '4A', true, false, false, true, false),
    new Frame(358, 1, 12, 'Box 1', '4B', false, true, true, true, false),
    new Frame(359, 1, 12, 'Box 1', '5A', true, true, true, false, false),
    new Frame(360, 1, 12, 'Box 1', '5B', false, false, false, true, false),
    new Frame(361, 2, 12, 'Box 2', '1A', false, true, false, false, false),
    new Frame(362, 2, 12, 'Box 2', '1B', false, true, true, false, true),
    new Frame(363, 2, 12, 'Box 2', '2A', false, true, false, true, true),
    new Frame(364, 2, 12, 'Box 2', '2B', false, true, true, true, false),
    new Frame(365, 2, 12, 'Box 2', '3A', false, true, true, false, true),
    new Frame(366, 2, 12, 'Box 2', '3B', true, false, true, true, true),
    new Frame(367, 2, 12, 'Box 2', '4A', true, false, false, true, true),
    new Frame(368, 2, 12, 'Box 2', '4B', true, false, true, false, true),
    new Frame(369, 2, 12, 'Box 2', '5A', true, false, true, true, false),
    new Frame(370, 2, 12, 'Box 2', '5B', false, false, true, false, false),
    new Frame(371, 3, 12, 'Box 3', '1A', true, true, true, false, false),
    new Frame(372, 3, 12, 'Box 3', '1B', false, false, false, true, false),
    new Frame(373, 3, 12, 'Box 3', '2A', true, true, false, false, true),
    new Frame(374, 3, 12, 'Box 3', '2B', true, false, true, false, true),
    new Frame(375, 3, 12, 'Box 3', '3A', false, true, false, false, true),
    new Frame(376, 3, 12, 'Box 3', '3B', false, true, true, false, false),
    new Frame(377, 3, 12, 'Box 3', '4A', true, false, true, true, true),
    new Frame(378, 3, 12, 'Box 3', '4B', false, true, true, false, false),
    new Frame(379, 3, 12, 'Box 3', '5A', true, true, false, false, true),
    new Frame(380, 3, 12, 'Box 3', '5B', true, false, true, true, false),
    new Frame(381, 1, 13, 'Box 1', '1A', false, false, true, true, false),
    new Frame(382, 1, 13, 'Box 1', '1B', false, false, true, true, true),
    new Frame(383, 1, 13, 'Box 1', '2A', true, false, true, false, false),
    new Frame(384, 1, 13, 'Box 1', '2B', true, true, false, true, true),
    new Frame(385, 1, 13, 'Box 1', '3A', true, false, false, false, false),
    new Frame(386, 1, 13, 'Box 1', '3B', false, false, true, true, true),
    new Frame(387, 1, 13, 'Box 1', '4A', false, true, false, false, false),
    new Frame(388, 1, 13, 'Box 1', '4B', true, false, false, true, true),
    new Frame(389, 1, 13, 'Box 1', '5A', true, false, false, true, true),
    new Frame(390, 1, 13, 'Box 1', '5B', false, true, true, false, true),
    new Frame(391, 2, 13, 'Box 2', '1A', false, false, false, true, false),
    new Frame(392, 2, 13, 'Box 2', '1B', false, true, false, true, false),
    new Frame(393, 2, 13, 'Box 2', '2A', false, false, true, false, true),
    new Frame(394, 2, 13, 'Box 2', '2B', false, true, false, true, false),
    new Frame(395, 2, 13, 'Box 2', '3A', false, false, false, false, false),
    new Frame(396, 2, 13, 'Box 2', '3B', true, true, true, true, false),
    new Frame(397, 2, 13, 'Box 2', '4A', false, true, true, false, true),
    new Frame(398, 2, 13, 'Box 2', '4B', true, true, true, true, true),
    new Frame(399, 2, 13, 'Box 2', '5A', true, true, true, true, false),
    new Frame(400, 2, 13, 'Box 2', '5B', true, false, true, true, false),
    new Frame(401, 3, 13, 'Box 3', '1A', false, true, true, true, false),
    new Frame(402, 3, 13, 'Box 3', '1B', false, false, false, true, true),
    new Frame(403, 3, 13, 'Box 3', '2A', false, false, true, true, false),
    new Frame(404, 3, 13, 'Box 3', '2B', false, true, true, false, true),
    new Frame(405, 3, 13, 'Box 3', '3A', false, false, false, false, false),
    new Frame(406, 3, 13, 'Box 3', '3B', true, true, true, false, false),
    new Frame(407, 3, 13, 'Box 3', '4A', false, false, false, false, false),
    new Frame(408, 3, 13, 'Box 3', '4B', true, true, false, false, false),
    new Frame(409, 3, 13, 'Box 3', '5A', false, true, false, false, false),
    new Frame(410, 3, 13, 'Box 3', '5B', true, true, false, false, false)

  ]);
  public frames$ = this._frames.asObservable();

  constructor() { }

  getFramesByInspectionAndBox(inspectionId: number, boxName: string): Observable<Frame[]> {
    return this.frames$.pipe(
      map(frames =>
        frames.filter(
          frame => frame.inspection_id === inspectionId && frame.box_name === boxName
        )
      )
    );
  }

  addFrame(newFrame: Frame) {
    const currentFrames = this._frames.getValue();
    this._frames.next([...currentFrames, newFrame]);
  }

  getNextID(): Observable<number> {
    return this.frames$.pipe(
      map(frames => {
        if (frames.length === 0) {
          return 1;
        }
        const highestID: number = Math.max(...frames.map(frame => frame.frame_id));
        return highestID + 1;
      })
    )
  }
}
